# Generated by Django 3.1.2 on 2020-10-24 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyTest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=80, null=True)),
                ('patient', models.CharField(blank=True, max_length=80, null=True)),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('detail', models.JSONField()),
            ],
        ),
    ]
